#!/usr/bin/env bash
# Displays info about subdomains

# Function to get record type and destination for a subdomain
get_subdomain_info () {
    subdomain=$2
    dig_output=$(dig +noall +answer "$subdomain.$domain")
    record_type=$(echo "$dig_output" | awk '{print $4}')
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if subdomain parameter is not provided
if [[ $# -eq 1 ]]; then
    # If no subdomain provided, display information for default subdomains
    domain=$1
    get_subdomain_info "$domain" www
    get_subdomain_info "$domain" lb-01
    get_subdomain_info "$domain" web-01
    get_subdomain_info "$domain" web-02
fi

# Check if subdomain parameter is provided
if [[ $# -eq 2 ]]; then
    # If subdomain provided, display information for that subdomain
    domain=$1
    subdomain=$2
    get_subdomain_info "$domain" "$subdomain"
fi
