#!/usr/bin/env bash
# Displays info about subdomains

# Function to get record type and destination for a subdomain
get_subdomain_info () {
    domain=$1
    subdomain=$2
    dig_output=$(dig +short "$subdomain"."$domain")
    record_type=$(echo "$dig_output" | awk '{print $1}')
    destination=$(echo "$dig_output" | awk '{print $2}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if domain parameter is provided
if [[ -z $1 ]]; then
    echo "Please provide a domain name as the first parameter"
    exit 1
fi

# Check if subdomain parameter is provided
if [[ -z $2 ]]; then
    # If no subdomain provided, display information for default subdomains
    domain=$1
    get_subdomain_info "$domain" www
    get_subdomain_info "$domain" lb-01
    get_subdomain_info "$domain" web-01
    get_subdomain_info "$domain" web-02
else
    # If subdomain provided, display information for that subdomain only
    domain=$1
    subdomain=$2
    get_subdomain_info "$domain" "$subdomain"
fi
