#!/usr/bin/env bash
# Transfer a file to a remote server using scp

path_to_file=$1
server_ip=$2
username=$3
path_to_ssh_key=$4

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$server_ip:~"
fi
