#!/usr/bin/env bash
# Install nginx
apt-get update
apt-get install nginx -y

# Configure nginx
sed -i 's/^.*root.*$/root \/var\/www\/html;/' /etc/nginx/sites-enabled/default
echo "Hello World!" > /var/www/html/index.html

# Restart nginx
/etc/init.d/nginx restart
