#!/usr/bin/env bash
# Install nginx
apt-get update
apt-get install nginx -y

# create directories
mkdir -p /etc/nginx/html

# Configure nginx at server side
echo "Hello World!" > /etc/nginx/html/index.html

# Start nginx
/etc/init.d/nginx restart
