#!/usr/bin/env bash
# Install nginx and write "Hello World" to /var/www/html/index.html
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html

# Create a redirection
sudo sed -i "9i\ \n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.facebook.com\/;\n\t}" /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart

