#!/usr/bin/env bash
# Redirect a page

# Install nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create index.html file
echo "Hello World!" > /var/www/html/index.html

# now let's redirect a page to another page
sudo sed -i '/server_name _;/a\ \tlocation /redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/results?search_query=girmachew+zewdie;\n\t}' /etc/nginx/sites-available/default

# reload nginx
sudo /etc/init.d/nginx reload
