#!/usr/bin/env bash
# Custom 404 page

# Write a custom 404 html page
echo "Ceci n'est pas une page" > /var/www/html/404.html

string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string/" /etc/nginx/sites-available/default

# restart nginx
sudo service nginx restart
