#!/usr/bin/env bash
# Redirect a page permanently
# Install nginx
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
ufw allow 'Nginx HTTP'

# Create a redirection
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}"
sudo sed -i "/server_name _;/a\\$redirect" /etc/nginx/sites-available/default

# custom 404 page
custom_error_page="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "/server_name _;/a\\$custom_error_page" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
