#!/bin/bash
# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy to send traffic to web-01 and web-02 using a roundrobin algorithm
echo "
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 160306-web-01 100.25.167.139:80 check
    server 160306-web-02 54.172.232.30:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Start HAProxy service
sudo service haproxy restart
