#!/usr/bin/env bash
# Configure Nginx to run on port 80

# Remove the enabled default Nginx configuration file
sudo rm -rf /etc/nginx/sites-enabled/default

# Create a symbolic link between your /etc/nginx/sites-available/default and /etc/nginx/sites-enabled/
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Start/restart Nginx
sudo service nginx restart
