#!/usr/bin/env bash
# A bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself
# when receiving a SIGQUIT or SIGTERM signal

function terminator {
	# Deletes the file /var/run/myscript.pid
	rm /var/run/myscript.pid
	# Terminates itself
	exit
}

# Create the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2

	# Displays I hate the kill command when receiving a SIGINT signal
	trap 'echo "Y U no love me?!"' SIGINT
	# Displays I hate the kill command when receiving a SIGTERM signal
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	# Deletes the file /var/run/myscript.pid and terminates itself
	trap 'terminator' SIGQUITgit 
done
