#!/usr/bin/env bash
# A bash script that displays numbers from 1 to 100.
# Requirements:
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

# initialize the loop counter
i=1

# loop from 1 to 100
while [ $i -le 100 ]
do
	# check if the loop counter is a multiple of 3 and 5
	# if so, print "FizzBuzz"
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	# check if the loop counter is a multiple of 3
	# if so, print "Fizz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	# check if the loop counter is a multiple of 5
	# if so, print "Buzz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	# otherwise, print the loop counter
	else
		echo $i
	fi

	# increment the loop counter
	i=$((i+1))
done
