#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using until loop

# A variable is initialized to 1
i=1

# Until loop while the condition is false
until [ $i -ge 11 ]
do
	# Print "Best School"
	echo "Best School"
	# Increment the variable by 1
	(( i++ ))
done
