#!/usr/bin/env bash
# A bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

# The content of the current directory
for file in *
do
	# In a list format
	# Where only the part of the name after the first dash is displayed
	echo "$file" | cut -d '-' -f2
done
