#!/usr/bin/env bash
# configure web-01 so that its firewall redirects port 8080/TCP to port 80/TCP.

# Set the default forwarding policy to ACCEPT
sudo sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw

# Before adding a new rule, make sure that the change takes effect in configuration file
sudo ufw reload

# Allow incoming traffic on port 8080
sudo ufw allow 8080/tcp

# Add a ufw rule to forward incoming traffic on port 8080 to port 80
sudo ufw route allow proto tcp from any to any port 8080 forward to 54.209.182.89 port 80

# Save and reload the ufw firewall
sudo ufw --force enable

# Verify that the port forwarding rule is added
# sudo ufw show added
