#!/usr/bin/env bash
# Adds a rule to forward port 8080 to port 80

# Allow incoming traffic on port 8080
sudo ufw allow 8080/tcp

# Forward port 8080 to port 80
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80

# Save the iptables rules with silent mode
sudo iptables-save | sudo tee /etc/iptables.sav > /dev/null

# Reload ufw to apply the changes
sudo ufw --force reload
